# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WBSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WBSwift
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'YYModel'

end
